/* eslint-disable no-unused-vars */
export enum ENUM_ORDER_STATUS {
  PENDING = "PENDING",
  PROCESS = "PROCESS",
  SHIPPING = "SHIPPING",
  SUCCESS = "SUCCESS",
  CANCEL = "CANCEL",
}

export enum ENUM_PAYMENT_STATUS {
  CHECKING = "CHECKING",
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAIL = "FAIL",
}

export enum ENUM_ORDER_PROCESS {
  ORDER_TIME = "ORDER_TIME",
  PROCESS_TIME = "PROCESS_TIME",
  PAYMENT_TIME = "PAYMENT_TIME",
  SHIP_TIME = "SHIP_TIME",
  COMPLETED_TIME = "COMPLETED_TIME",
  CANCEL_TIME = "CANCEL_TIME",
}

export enum ENUM_PAYMENT_METHOD {
  COD = "COD",
  CARD = "CARD",
  CASH = "CASH",
  VNPAY = "VNPAY",
  BANKING = "BANKING",
}
