export enum typeCel {
  TEXT = "text",
  DATE = "date",
  LINK = "link",
  STATUS = "status",
  THUMBNAIL = "thumbnail",
  SELECT = "select",
  SELECT_IMAGE = "select_image",
  AVATAR = "avatar",
  BUTTON = "button",
  BUTTON_LINK = "buttonLink",
  GROUP = "group",
  PUBLIC = "public",
  INPUT = "input",
  INPUT_NUMBER = "input_number",
}
